version: "3"
services:
    gm-back:
        build: ./back
        ports: 
            - "3080:3080"
        depends_on:
            gm-db:
                condition: service_healthy
        networks: 
            - reactapp
            - api
        hostname: backend

    gm-front:
        build:
            context: ./front
        ports:
            - "8080:8080"
        depends_on: 
            - gm-back
        networks:
            - reactapp
        hostname: frontend

    gm-db:
        image: mysql
        ports:
            - "3200:3306"
        volumes:
            - ./database/mysql:/var/lib/mysql
            - ./database/files/init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - LANG=C.UTF-8
        networks: 
            - api
        hostname: database
        healthcheck: 
            test: bash -c "[ -d /var/lib/mysql/groupomania ]"
            interval: 3s
            timeout: 30s
            retries: 10

networks:
    api:
        name: gm-back-ntwk
    reactapp:
        name: gm-front-ntwk