version: "3"
services:
    back:
        command: ["npm", "start"]
        
    front:
        build:
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
            - "443:443"