version: "3"
services:
    gm-back:
        volumes:
            - ./back/app:/app/app:ro
            - ./back/logs:/app/logs
            - ./back/images:/app/images
            - ./back/docs/jsdoc:/app/docs/jsdoc
            - /app/node_modules
            
    gm-front:
        build:
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes:
            - ./front/src:/app/src:ro
            - /app/node_modules