version: "3"
services:
    back:
        build: ./back
        ports: 
            - "3080:3080"
        depends_on:
            - db
        networks: 
            - reactapp
            - default
        hostname: backend

    front:
        build:
            context: ./front
        ports:
            - "80:80"
        depends_on: 
            - back
        networks:
            - reactapp
        hostname: frontend

    db:
        image: mysql
        ports:
            - "3200:3306"
        volumes:
            - ./database/mysql:/var/lib/mysql
            - ./database/files/init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - LANG=C.UTF-8
        networks: 
            - default
        hostname: database

networks:
    default:
        name: gm-back-ntwk
    reactapp:
        name: gm-front-ntwk