version: "3"
services:
    back:
        volumes:
            - ./back/app:/app/app:ro
            - ./back/logs:/app/logs
            - ./back/images:/app/images
            - /app/node_modules
            
    front:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./front/src:/app/src:ro
            - /app/node_modules