version: "3"
services:
    back:
        volumes: 
            - ./back/logs:/app/logs
            - ./back/images:/app/images
        command: ["npm", "start"]
        
    front:
        build:
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
            - "443:443"